version: '3'
services:
  php:
    build: ./docker/php
    ports: 
      - "80:80"
      - "8080:8080"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mariadb
  mariadb:
    build: ./docker/mariadb
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql
    environment:
      - TZ:Asia/Tokyo
      - MYSQL_ROOT_PASSWORD:pass
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mariadb
